location: .gitman
sources:
  - repo: git@github.com:LASER-Robotics/px4_firmware-ROS2-.git
    name: px4_firmware-ROS2-
    rev: release/1.15
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/micro_xrce_dds_agent.git
    name: micro_xrce_dds_agent
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/micro_xrce_dds_agent
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/px4_msgs.git
    name: px4_msgs
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_uav_px4_api.git
    name: laser_uav_px4_api
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_uav_px4_api
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_uav_managers.git
    name: laser_uav_managers
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_uav_controllers.git
    name: laser_uav_controllers
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_uav_planner.git
    name: laser_uav_planner
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_uav_planner
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_msgs.git
    name: laser_msgs
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_uav_simulation.git
    name: laser_uav_simulation
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_uav_simulation
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_gazebo_resources.git
    name: laser_gazebo_resources
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_gazebo_resources
    scripts:
      - git submodule update --init --recursive
sources_locked:
groups:
  -
default_group: ''
