name: simulation
root: ~/laser_uav_system_ws/src
startup_window: gazebo
pre_window:
windows:
  - gazebo:
      layout: even-horizontal
      panes:
        - sleep 1; cd ~/git/laser_uav_system/ros_packages/px4_firmware; make px4_sitl gazebo-classic
        - sleep 3; MicroXRCEAgent udp4 -p 8888
  - api:
      layout: even-horizontal
      panes:
        - sleep 1; ros2 launch laser_uav_px4_api api.launch.py
  - free_cmd:
      layout: tiled
      panes:
        - 'history -s ros2 topic list'

