name: Main Build

on:
  push:
    branches: [ main ]
  paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute install.sh
        run: ./install.sh
